version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip doordash_lambda_function.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package.zip s3://s3-data-lake-san/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name doordash-lambda-function --s3-bucket s3-data-lake-san --s3-key deployment_package.zip
      - echo "Deployment complete!"
